name: Build docker image and run node tests (GHCR)

on:
  push:
    branches: [ develop, main, fork_8 ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag to publish (defaults to branch name or short SHA fallback)'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: [self-hosted, linux, X64, hc]

    outputs:
      sha_short: ${{ steps.setvars.outputs.sha_short }}
      tag: ${{ steps.setvars.outputs.tag }}
      image_tag: ${{ steps.setvars.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # replaces manual submodule init/update

      - name: Set variables
        id: setvars
        shell: bash
        run: |
          SHA_SHORT="${GITHUB_SHA::7}"

          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
          else
            # Use ref_name when running on push; otherwise fallback to short SHA
            if [ -n "${{ github.ref_name }}" ]; then
              TAG="${{ github.ref_name }}"
            else
              TAG="manual-${SHA_SHORT}"
            fi
          fi

          echo "sha_short=$SHA_SHORT" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "image_tag=ghcr.io/${{ github.repository_owner }}/zkevm-prover:${TAG}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (executor)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          target: executor
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zkevm-prover:${{ steps.setvars.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/zkevm-prover:${{ steps.setvars.outputs.sha_short }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  # node-tests:
  #   needs: build-docker
  #   uses: 0xPolygonHermez/zkevm-node/.github/workflows/test-from-prover.yml@develop
  #   with:
  #     prover_image: ${{ needs.build-docker.outputs.image_tag }}
  #   secrets:
  #     # If GHCR package is private, that workflow needs a token with read:packages to docker login ghcr.io
  #     GHCR_READ_TOKEN: ${{ secrets.GITHUB_TOKEN }}
